BASE_TASK_CONFIG_PATH: "/home/haardshah/habitat-submission/configs/train_pose_estimation.local.rgbd.yaml"
TRAINER_NAME: "ppo"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "pretrained2/tensorboard"
VIDEO_DIR: "pretrained2/video_dir"
# To evaluate on all episodes, set this to -1
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "pretrained2/new_checkpoints"
# NUM_PROCESSES: 2
NUM_PROCESSES: 1
# SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "pretrained2/new_checkpoints"
NUM_UPDATES: 10000
LOG_INTERVAL: 5
CHECKPOINT_INTERVAL: 50
MODEL_PATH: "data/ckpt.7.pth"
LOG_FILE: "pretrained2/train.log"

RL:
  PPO:
    # ppo params
    clip_param: 0.1
    ppo_epoch: 4
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    num_steps: 128
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    reward_window_size: 50
